language: node_js
sudo: false
node_js:
- lts/*
after_success:
- "./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls"
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  skip_cleanup: true
  api_key:
    secure: jj0xahH8OPIRdM95l/b1KENIC++WpeZtiE0w2ATKDBrCYyUD+KBVaAHeme3hTc/3mclGQINVY9WHjcadtJmcYhbRS8wXO61q3ryeWrDnXUgjLhJ6M2XbR9u1PA3RuTrjHnZzySBanaHlytCtQWj/tdVqlsvL2VoZFAhYFqqO3ha0/ViTZOhA299ieCC4dqEwP3gKSEja1du8dfYbmDKLbehS+Lxw8z45PcUiQ3FN4hE4Qe+gqpOOY20rWRaiiH2Gt1f2SOKokUadBX2sWoK9/Pxgsd37egECb30zJp/fAf2XaErBVLtkj+9wo37yzwKMUfNK2b5JygLxlzGW+p57I/3mWiTijifjlCNCWvS3RFdVaDqv5y3WciAE2rTYgAJQTLPSUcdVhUS5XzzsF9oNYHZHsqzTnXvyfyRGH4tKZIZeIJJ2XAe3KZLxbI/79C+v4bDBYc2ElrThfunEtngg9ZDpnHLrqR6lBxb1LUQgs9cL8UvaOcAs1ceHaZ1UAV1Mx8yRAoQkH8YJKC8kDD2tdIPAFQ+oqvR5nftnp2Opv4Z2eH08/NTef/EmhSJIFq/9vjj7hGTmG/b7a5stdxlDNtfY0koWnR0Mjv92X7obg+sygBw5vNuW7eTmxMagDj3rEFZ194wlr2JPr3ipW/4ex9PCFk2ffYI9OnWec+EDIhI=
  on:
    tags: true
    repo: flowbased/fbp-graph
